// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jcdatabase.DataAccess;

#nullable disable

namespace jcdatabase.Migrations
{
    [DbContext(typeof(JesterClubDbContext))]
    [Migration("20260128064708_JokeSeed")]
    partial class JokeSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JokeTag", b =>
                {
                    b.Property<int>("JokesJokeId")
                        .HasColumnType("int");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("int");

                    b.HasKey("JokesJokeId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("JokeTag");
                });

            modelBuilder.Entity("jcdatabase.Models.EmotionCounter", b =>
                {
                    b.Property<int>("JokeId")
                        .HasColumnType("int");

                    b.Property<string>("Emotion")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.HasKey("JokeId", "Emotion");

                    b.ToTable("EmotionCounters", t =>
                        {
                            t.HasCheckConstraint("CK_EmotionValue", "[Emotion] IN ('sleepy','none','happy','lol','lshic')");
                        });
                });

            modelBuilder.Entity("jcdatabase.Models.Joke", b =>
                {
                    b.Property<int>("JokeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JokeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JokeText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReleasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResponseSum")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JokeId");

                    b.HasIndex("UserId");

                    b.ToTable("Jokes");
                });

            modelBuilder.Entity("jcdatabase.Models.ResponseStatistic", b =>
                {
                    b.Property<int>("JokeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.HasKey("JokeId", "Day");

                    b.ToTable("ResponseStatistics");
                });

            modelBuilder.Entity("jcdatabase.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("jcdatabase.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JokeTag", b =>
                {
                    b.HasOne("jcdatabase.Models.Joke", null)
                        .WithMany()
                        .HasForeignKey("JokesJokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("jcdatabase.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("jcdatabase.Models.EmotionCounter", b =>
                {
                    b.HasOne("jcdatabase.Models.Joke", null)
                        .WithMany("EmotionCounters")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("jcdatabase.Models.Joke", b =>
                {
                    b.HasOne("jcdatabase.Models.User", "User")
                        .WithMany("Jokes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("jcdatabase.Models.ResponseStatistic", b =>
                {
                    b.HasOne("jcdatabase.Models.Joke", null)
                        .WithMany("ResponseStatistics")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("jcdatabase.Models.Joke", b =>
                {
                    b.Navigation("EmotionCounters");

                    b.Navigation("ResponseStatistics");
                });

            modelBuilder.Entity("jcdatabase.Models.User", b =>
                {
                    b.Navigation("Jokes");
                });
#pragma warning restore 612, 618
        }
    }
}
